# -*- makefile-gmake -*-

###########################
## Package configuration ##
###########################
.PHONY: all

all: all-generic

AUTHORS  = $(shell cat AUTHORS | tr '\n' ',' | cut -d, -f1,4 | tr ',' '-')

VERSION	  = 0.1
TARGET	  = liboblacs
TARGETEXT = liboblacs
PACKAGE	  = oblacs-$(AUTHORS)-$(VERSION)
