# -*- makefile-gmake -*-

.PHONY: announce version configure

version:
	@ echo "let number = \"$(VERSION)\"" > src/version.ml

announce:
	@ echo "Source configuration ..."

configure: announce version